spring.application.name: mall-web-schedule
spring.session.redis.namespace: session:${spring.application.name}
spring:
  datasource:
    table:
      prefix: 

user.type.name: 

wechat:
  user:
    url:
      refresh_token: 'https://api.weixin.qq.com/sns/oauth2/refresh_token?appid=%s&grant_type=refresh_token&refresh_token=%s'
